ui/components/canvas2d/src/Canvas2D.svelte
a recent change was a regression on this, so I revert.
setTimeout() allow a smoother drag than "wait"
=> allow smooth drag of input point

ui/apps/pixano/src/routes/+layout.svelte, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/core/src/components/modals/SelectModal.svelte, ui/components/core/src/components/modals/WarningModal.svelte, ui/components/imageWorkspace/src/ImageWorkspace.svelte, ui/components/imageWorkspace/src/components/LoadModelModal.svelte, ui/components/imageWorkspace/src/components/Toolbar.svelte, ui/components/imageWorkspace/src/lib/api/modelsApi.ts, ui/components/imageWorkspace/src/lib/stores/imageWorkspaceStores.ts, ui/components/imageWorkspace/src/lib/types/imageWorkspaceTypes.ts
Fixes pixano/pixano-project-manager#7
=> feat(front): Select models if more than one and display errors

ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte, ui/apps/pixano/src/lib/stores/datasetStores.ts, ui/apps/pixano/src/lib/types/pixanoTypes.ts, ui/apps/pixano/src/routes/+layout.svelte
Add back semantic search in new layout.
Fixes pixano/pixano-project-manager#9
=> feat(front): Add back semantic search in dataset page

ui/apps/pixano/src/components/layout/MainHeader.svelte, ui/apps/pixano/src/routes/+layout.svelte, ui/apps/pixano/src/routes/+page.svelte
Fixes pixano/pixano-project-manager#11
=> feat: Add loading indicator on homepage

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/api/boundingBoxesApi.ts, ui/components/canvas2d/src/components/PolygonGroup.svelte, ui/components/core/src/lib/types/objectTypes.ts, ui/components/imageWorkspace/src/ImageWorkspace.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ActionsTabs.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte, ui/components/imageWorkspace/src/components/ImageCanvas.svelte, ui/components/imageWorkspace/src/lib/api/objectsApi.ts
fixes pixano/pixano-project-manager#13
- Display loader when item is being saved
- Allow user to save when rectangle dimensions have been saved
- Display tooltip only if feature.category exists
=> feat(front): Improve save item changes 

ui/apps/pixano/src/components/layout/DatasetHeader.svelte, ui/apps/pixano/src/lib/stores/datasetStores.ts, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/api/boundingBoxesApi.ts, ui/components/canvas2d/src/components/PolygonGroup.svelte, ui/components/canvas2d/src/lib/types/canvas2dTypes.ts, ui/components/core/src/components/modals/ConfirmModal.svelte, ui/components/imageWorkspace/src/ImageWorkspace.svelte, ui/components/imageWorkspace/src/components/Features/TextInputFeature.svelte, ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte, ui/components/imageWorkspace/src/components/Toolbar.svelte, ui/components/imageWorkspace/src/lib/api/objectsApi.ts, ui/components/imageWorkspace/src/lib/settings/defaultFeatures.ts
Several small bug fixes / improvements:
- The point radius and polygon lines are now correlated with the zoom factor
- Bug fix on multiview for display and mask creation.
- Color change to harmonize creation tools (both rectangle and polygons).
- Modal to allow saving when switching items without saving.
- Display of a return button when the item does not exist.
- Display of "confidence" in tooltips only for model runs (not for ground truth).
Fixes pixano/pixano-project-manager#26
FIxes pixano/pixano-project-manager#21
=> fix(front): Improve multi-view and tool selection

ui/apps/pixano/src/components/dashboard/Dashboard.svelte, ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte, ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte, ui/apps/pixano/src/components/layout/DatasetHeader.svelte, ui/apps/pixano/src/components/layout/MainHeader.svelte, ui/apps/pixano/src/routes/+layout.svelte, ui/apps/pixano/src/routes/+page.svelte, ui/apps/pixano/src/routes/[dataset]/dashboard/+page.svelte, ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/core/src/components/modals/ConfirmModal.svelte, ui/components/core/src/components/modals/PromptModal.svelte, ui/components/core/src/components/modals/SelectModal.svelte, ui/components/core/src/components/modals/WarningModal.svelte, ui/components/core/src/components/ui/molecules/PrimaryButton.svelte, ui/components/core/src/components/ui/tabs/tabs-trigger.svelte, ui/components/core/src/components/ui/tooltip/tooltip-content.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ActionsTabs.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte, ui/components/imageWorkspace/src/components/Features/FeatureInputs.svelte, ui/components/imageWorkspace/src/components/Toolbar.svelte, ui/components/table/src/Table.svelte
- Various visual fixes, including:
- Colors
- Fonts
- Padding values
- z-index values
- Return to a dataset's main page by clicking on its name in the header
=> chore(front): Various visual fixes

pixano/data/item/item_view.py, ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte, ui/apps/pixano/src/routes/+layout.svelte
- Fix loading icon appearing when page is not changing
- Fix getDatasetItems not using default page number and size 
- Fix page number not resetting when switching datasets
- Fix error in backend when loading item with missing views
=> chore(front): Fix navigation issues

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/SceneTabContent.svelte
fix: pixano/pixano-project-manager#29
=> fix: Add default scene feature when loading for the first time

ui/components/imageWorkspace/src/ImageWorkspace.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabContent.svelte, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte
fix : pixano/pixano-project-manager#24
=> fix: Update object visibility in ObjectTabModelContent component

ui/components/canvas2d/src/api/boundingBoxesApi.ts, ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabModelContent.svelte, ui/components/imageWorkspace/src/components/Toolbar.svelte
fixes : pixano/pixano-project-manager#28
description: scale bounding box borders on transform
=> fix: Fixed scaling issue in addBBox function

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/imageWorkspace/src/components/LoadModelModal.svelte
fixes : pixano/pixano-project-manager#30
improve number of time we hit the api for : 
- loading new item
- loading embeddings
=> fix(front): Load embeddings only once a model is selected

ui/components/imageWorkspace/package.json, ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
fix : pixano/pixano-project-manager#37
=> fix(front): Generate unique IDs when saving new object

ui/components/canvas2d/src/Canvas2D.svelte, ui/components/core/src/lib/types/objectTypes.ts, ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
=> fix(front): Remove shapes when canceling the annotation, #60

ui/components/canvas2d/src/Canvas2D.svelte
=> feat(front): Destroy rectangle smart rectangle once smart mask is created

pixano/data/item/item_object.py
=> fix(back): Don't save review_state if None

ui/components/imageWorkspace/src/components/ImageInspector/ImageInspector.svelte
=> feat(front): Switch tabs order in image inspector

ui/components/imageWorkspace/src/lib/api/objectsApi.ts
#99 
Pre annotation objects are now sorted based on their X position (`bbox.coords[0`)
=> feat(front): Sort preannoted objects by axis

notebooks/models/interactive_annotation.ipynb
Fixes pixano/pixano-inference#1 in parallel with branch pixano/pixano-inference#2
- Update the interactive segmentation notebook for the new MobileSAM model added to Pixano Inference
=> feat(back): Add new MobileSAM model

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/feat_pull_request.md, .github/PULL_REQUEST_TEMPLATE/fix_pull_request.md
Fixes #132
Add issue and pull request templates using the GitHub template format
=> feat(ci): Add issue and pull request templates

ui/components/imageWorkspace/src/components/ImageCanvas.svelte
=> fix(front): Allow saving when deleting a selected object

ui/components/imageWorkspace/src/components/LoadModelModal.svelte
=> fix(front): add cancel option to no embeddings modal

ui/apps/pixano/src/components/layout/DatasetHeader.svelte
=> fix(front): Reset saveCurrentItemStore to false after navigating

ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
Fixes #155 
- Recommandation are now accurate for each pre annonation
- All object are highlighted with full opacity when pre annotation is over
=> fix(front): Recommandations for pre annotation are updated for each item

.github/workflows/lint.yml, .github/workflows/test.yml, notebooks/models/interactive_annotation.ipynb, notebooks/models/pre_annotation.ipynb, notebooks/models/semantic_search.ipynb
Fixes #198
Update GitHub actions and notebooks to refer to the new PyPI version of Pixano Inference instead of the GitHub version.
=> feat(ci): Update uses of Pixano Inference to PyPI

ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/components/CreatePolygon.svelte, ui/components/canvas2d/src/components/CreateRectangle.svelte, ui/components/canvas2d/src/components/LabelTag.svelte, ui/components/canvas2d/src/components/Rectangle.svelte, ui/components/core/src/lib/types/objectTypes.ts, ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte, ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
=> feat: Add box dimension when creating a bbox

docs/restAPI_reference/data_items.md, pixano/app/api/items.py, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/components/Rectangle.svelte, ui/components/core/src/api.ts, ui/components/core/src/lib/types/datasetTypes.ts, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte, ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte, ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyBox.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoPlayer.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts, ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts, ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts, ui/components/datasetItemWorkspace/src/lib/stores/videoViewerStores.ts, ui/tools/storybook/stories/components/workspaces/videoDatasetPayload.ts
Fixes #235
Adding a new is_key param to keypoint. We could by the way change the naming for keyBoxes to boxes since they are not all key now
=> fix(front): Improve video ux

pixano/__version__.py
see release notes for version 0.5.2
release 0.5.2
=> feat(back): change to version 0.5.2

pixano/__version__.py
=> feat(back) change to version 0.5.3

ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
=> feat: Add updated values to save payload

pixano/app/api/items.py, pixano/datasets/dataset.py, pixano/datasets/features/schemas/tracklet.py
Save - back side
Read video - back side : tracklet table
=> feat(back): save item + video: Tracklet table handle

pixano/app/api/items.py
Adaptation needed for empty objects (bbox/mask) (fake null) for load and save
Also, fix missing conversion from/to compressed rle from/to uncompressed rle.
Need to detect empty bbox/mask to send / save correct value
=> fix(back): save and load for empty bbox and mask

ui/components/canvas2d/src/api/keypointsApi.ts, ui/components/canvas2d/src/components/CreateKeypoints.svelte, ui/components/canvas2d/src/components/ShowKeypoint.svelte, ui/components/datasetItemWorkspace/src/lib/settings/keyPointsTemplates.ts
=> fix: Adapt keypoints creation background size

pixano/__version__.py
version 0.5.4
change: https://github.com/pixano/pixano/pull/279
=> change version to 0.5.4

ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
Fixes #283 
The sliders will now work as intended.
=> fix(front): fix sliders linked together

pixano/datasets/dataset.py, pixano/datasets/dataset_schema.py, tests/datasets/test_dataset.py, tests/datasets/test_dataset_schema.py
Add functions to update, add and delete in datasets
Add posibility to get data from tables from the item_id and not only their id.
=> Finish dataset crud

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
Tracklets are now per view, we want to see them for each view
Tracks are divided in *num_view* lines, displaying tracklets per view
=> tracklets per view

.github/workflows/lint_and_format_back.yml, .github/workflows/lint_and_format_front.yml, .github/workflows/test_back.yml, pyproject.toml
Trigger linters, formatters and tests when CI configs are changed.
=> Add tests when CI config changes

.github/workflows/lint_and_format_back.yml, .github/workflows/test_back.yml, .pre-commit-config.yaml, pyproject.toml, tests/datasets/builders/test_dataset_builder.py
=> Add python 3.11

pixano/app/api/items.py
Tracking dataset would take very long to load.
Fixes #313 
Changed the data loading paradigm where a buffer of correspondence is first created and then used to load all data fater.
=> tracking: data opening optimization

pixano/datasets/dataset.py, pixano/datasets/dataset_schema.py, pixano/datasets/features/schemas/embeddings/embedding.py, tests/datasets/conftest.py, tests/datasets/features/schemas/embeddings/test_embedding.py, tests/datasets/test_dataset.py, tests/datasets/test_dataset_schema.py, tests/fixtures/datasets/dataset_item.py, tests/fixtures/datasets/dataset_schema.py, tests/fixtures/datasets/features/embedding.py
Add the `compute_embeddings` method in dataset to ease the process of using embeddings functions.
=> Add compute embeddings

pixano/app/main.py, pixano/app/routers/browser.py, pyproject.toml, tests/app/routers/test_browser.py, tests/conftest.py, tests/features/schemas/embeddings/test_embedding.py, tests/fixtures/app/routers/browser.py
Add semantic search to browse items.
=> Add semantic search to browse items

pixano/app/main.py, pixano/app/models/__init__.py, pixano/app/models/dataset_info.py, pixano/app/models/datasets.py, pixano/app/models/sources.py, pixano/app/models/utils.py, pixano/app/routers/annotations.py, pixano/app/routers/datasets.py, pixano/app/routers/embeddings.py, pixano/app/routers/entities.py, pixano/app/routers/items.py, pixano/app/routers/sources.py, pixano/app/routers/utils.py, pixano/app/routers/views.py, pixano/datasets/dataset.py, pixano/datasets/dataset_info.py, tests/app/models/test_dataset_info.py, tests/app/models/test_source.py, tests/app/routers/test_annotations.py, tests/app/routers/test_datasets.py, tests/app/routers/test_embeddings.py, tests/app/routers/test_entities.py, tests/app/routers/test_items.py, tests/app/routers/test_source.py, tests/app/routers/test_utils.py, tests/app/routers/utils.py, tests/conftest.py, tests/datasets/test_dataset.py, tests/datasets/test_dataset_info.py, tests/fixtures/app/models/dataset_info.py
=> Improve API

pixano/datasets/builders/dataset_builder.py, pixano/datasets/builders/folders/base.py, pixano/features/schemas/annotations/bbox.py, pixano/features/schemas/annotations/camcalibration.py, pixano/features/schemas/annotations/compressed_rle.py, pixano/features/schemas/annotations/keypoints.py, pixano/features/schemas/annotations/tracklet.py, pixano/features/schemas/source.py, tests/datasets/builders/test_dataset_builder.py, tests/datasets/builders/test_folders.py, tests/features/schemas/test_source.py, tests/fixtures/datasets/builders/builder.py
Add source handler in builders
Add OTHER group in SourceKind
=> Add source to builder

pixano/app/routers/annotations.py, pixano/app/routers/browser.py, pixano/app/routers/embeddings.py, pixano/app/routers/entities.py, pixano/app/routers/items.py, pixano/app/routers/items_info.py, pixano/app/routers/sources.py, pixano/app/routers/utils.py, pixano/app/routers/views.py, pixano/datasets/dataset.py, tests/app/routers/test_annotations.py, tests/app/routers/test_embeddings.py, tests/app/routers/test_entities.py, tests/app/routers/test_items.py, tests/app/routers/test_items_info.py, tests/app/routers/test_source.py, tests/app/routers/test_utils.py, tests/app/routers/test_views.py, tests/app/routers/utils.py, tests/datasets/test_dataset.py
Add in the backend and API Rest the parameter 'where' to allow finer search on tables.
=> Add possibility to use where statement for getting data

pixano/app/main.py, pixano/app/routers/browser.py, tests/fixtures/app/app.py, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/apps/pixano/vite.config.ts
back: add mount for media_dir,
front: add route, remove ds.media_dir hack + change data to media
=> fix media_dir change for front

pixano/app/models/base_schema.py, pixano/datasets/builders/dataset_builder.py, pixano/datasets/dataset_info.py, pixano/features/schemas/base_schema.py, tests/app/models/test_base_schema.py, tests/datasets/builders/test_dataset_builder.py, tests/datasets/test_dataset_info.py, tests/features/schemas/test_base_schema.py
=> Add constraint to prevent id with whitespaces

ui/components/core/src/api.ts
Navigation in browser (page change) broken
Fixes #
=> fix browser navigation

ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/api/rectangleApi.ts, ui/components/canvas2d/src/components/Rectangle.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts, ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
Some bugs / weird behaviour with highlight and edition flag of objects, in video mode
=> correction for higlight & editing status

ui/components/core/src/api.ts, ui/components/core/src/lib/types/datasetTypes.ts, ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts
Features in the Inspector display only top level entity features
Fixes https://github.com/pixano/pixano-project-manager/issues/72
Take features from all available data TopEntity-subEntity-annotation
TMP: origin (table (+ view for annotatin level features) of feature is displayed in feature label (usefull but ugly as it is now)
TODO in another PR: better display
=> display features extent

docs/tutorials/segmentation_powered_by_sam.md, mkdocs.yml, pixano/app/main.py, pixano/app/routers/models.py, pixano/datasets/dataset_info.py, ui/apps/pixano/src/routes/+layout.svelte, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/apps/pixano/vite.config.ts, ui/components/canvas2d/src/Canvas2D.svelte, ui/components/canvas2d/src/api/boundingBoxesApi.ts, ui/components/core/src/api.ts, ui/components/core/src/lib/types/datasetTypes.ts, ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte, ui/components/datasetItemWorkspace/src/lib/api/modelsApi.ts, ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
PR to bring back SAM for 0.6.0 release.
=> Bring back SAM

.pre-commit-config.yaml, mkdocs.yml, pyproject.toml
=> Update hooks and pyproject.toml

ui/apps/pixano/src/lib/stores/datasetStores.ts, ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/canvas2d/src/components/PolygonGroup.svelte, ui/components/canvas2d/src/components/Rectangle.svelte, ui/components/core/src/api.ts, ui/components/core/src/lib/types/datasetTypes.ts, ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/Features/AutoCompleteFeatureInput.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts, ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts, ui/components/datasetItemWorkspace/src/lib/constants.ts, ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts
Sources were not managed at all in front
Fixes https://github.com/pixano/pixano-project-manager/issues/76
Correctly set sources, dispatch entities in inspector according to sources
Annotations created within pixano app are sourced with a common Pixano source (created and saved if not present)
{id: "pixano_source", kind: "other", name: "Pixano"}
=> manage sources

ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
xyxy coordinates were not converted to xywh to display in the frontend if they were already denormalized
Fixes #364
Separate the bounding box xyxy to xywh conversion step from the denormalization step in frontend
=> Separate bounding box xywh conversion from denormalization in frontend

pixano/features/schemas/annotations/info_extraction.py, tests/features/schemas/annotations/test_information_extraction.py
=> fix : add annotation_ref in Annotation TextSpan

ui/components/canvas2d/src/Canvas2D.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
For ease of use, shortcuts requested for play/pause and step forward / backward
Play/Pause : space
Step forward: right arrow
Step backward: left arrow
Note: the step ones can be kept down to "play" forward/backward while pressing arrow
=> Add shortcuts for play actions

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/components/core/src/api/addSchemas.ts, ui/components/core/src/api/index.ts, ui/components/core/src/api/updateSchemas.ts, ui/components/core/src/lib/types/dataset/datasetTypes.ts
When merging tracks, or in any case where we make many changes before save, front fetch far too much request
Fixes #
Take advantage of pixano back API which allows to send an array of items (POST & PUT) instead of a fetch per item
=> gather save by method, group, table

ui/apps/pixano/src/components/layout/DatasetHeader.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
Fixes #413 
"shift" modifier to change page (datasetItem)
=> shift for datasetItem change left&right arrow

pixano/datasets/builders/folders/base.py
Fixes #415 
If no metadata.jsonl found, just parse for image files as usual
=> allow no jsonl

ui/apps/pixano/src/components/layout/DatasetHeader.svelte
No tooltip for shift + left/right arrow, for dataset item navigation 
add key shortcut in buttons tooltips
=> add key shortcut in tooltip

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
Fixes #426 
remove it from entities store
(also some minor code rework: moved down tracks by using store)
=> remove track from timeline if last tracklet

mkdocs.yml, pixano/inference/__init__.py, pixano/inference/client.py, pyproject.toml, tests/conftest.py, tests/fixtures/inference/__init__.py, tests/fixtures/inference/client.py, tests/inference/__init__.py, tests/inference/test_client.py
This PR adds a  client for Pixano-inference to prepare its comeback.
=> Add pixano-inference client

.github/workflows/test_back.yml, pixano/datasets/exporters/__init__.py, pixano/datasets/exporters/dataset_exporter.py, pixano/datasets/exporters/default.py, pixano/features/__init__.py, pixano/features/schemas/__init__.py, pixano/features/schemas/schema_group.py, tests/datasets/exporters/__init__.py, tests/datasets/exporters/test_dataset_exporter.py, tests/datasets/exporters/test_default.py, tests/features/schemas/test_schema_group.py
Fix partially #420 . We should still add back exporters and importers for known datasets such as COCO.
Add Base and Default exporters for the new Python API.
=> Add Base and default exporters

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedEntity.ts
Fixes #428 
thumbnails is now derived from entities, so any change made to this store is reflected in thumbnails
=> Refresh thumbnails whenever needed

ui/components/datasetItemWorkspace/src/components/Toolbar/FusionTool.svelte
Shortcuts requested for "Validate" and "Abort" in track association
added "Enter" for Validate and "Escape" for Abort
=> track fusion: add shortcuts for validate and abort

.github/workflows/lint_and_format_back.yml, .github/workflows/test_back.yml, pyproject.toml
=> Add python3.13 support

ui/components/core/src/lib/types/dataset/annotations/Message.ts, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte, ui/components/datasetItemWorkspace/src/lib/stores/mutations/addAnswer.ts, ui/components/datasetItemWorkspace/src/lib/stores/mutations/updateMessageContent.ts, ui/components/datasetItemWorkspace/src/lib/utils/createNewAnswer.ts, ui/components/datasetItemWorkspace/src/lib/utils/createUpdatedAnswer.ts, ui/components/datasetItemWorkspace/src/lib/utils/createUpdatedMessage.ts, ui/components/vqaCanvas/src/components/FormattedAnswer.svelte, ui/components/vqaCanvas/src/components/MultipleChoiceAnswer.svelte, ui/components/vqaCanvas/src/components/OpenAnswer.svelte, ui/components/vqaCanvas/src/components/QuestionForm.svelte, ui/components/vqaCanvas/src/components/SingleChoiceAnswer.svelte, ui/components/vqaCanvas/src/lib/types/ContentChangeEvent.ts, ui/components/vqaCanvas/src/lib/utils/answerChoicesToCheckboxsState.ts, ui/components/vqaCanvas/src/lib/utils/checkboxsStateToAnswerChoices.ts, ui/components/vqaCanvas/src/lib/utils/deserializeMessageContent.ts, ui/components/vqaCanvas/src/lib/utils/index.ts, ui/components/vqaCanvas/src/lib/utils/isQuestionCompleted.ts, ui/components/vqaCanvas/src/lib/utils/serializeMessageContent.ts, ui/tools/storybook/stories/testing/datasets/mockVqaDatasetItem.ts
When no answer exists for a question, the inputs are not displayed
- Add function to create a new message corresponding to the answer of a user. The system works as follows :
- If the current user already answered, the question is completed with his answer. If the user changes it, it updates the existing object in db
- Otherwise, an empty answer is displayed by default and on the first submit, a new message for this user is created
- Update the Message model in the frontend to match with the definition of the backend
=> feat: handle adding new answers to question

ui/components/core/src/lib/types/dataset/annotations/Annotation.ts, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedObject.ts
- total count of object wrongly counts Conversations
- inference_metadata is wrongly asked to user at creation time
- inference_metadata is not set at creation time, which lead to a zod error
- remove inference_metadata field from user's features,
- set default inference_metadata value at creation
- do not count conversations in Objects total count.
=> inference_metadata field front fixes + object total count fix

.github/workflows/docker.yml, .github/workflows/publish.yml
=> Add arm platform

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte, ui/apps/pixano/vite.config.ts, ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
regex used in vite.config.ts do not properly handle routes prefix "models" and "app_models"
- fixed regex
- remove some dev logs
=> fix regex vite.config

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte, ui/components/vqaCanvas/src/VqaArea.svelte, ui/components/vqaCanvas/src/features/addQuestion/components/AddQuestionModal.svelte
It can take some time to generate question or answer. 
Show a loading (or working) icon while waiting for response
=> show load icon while generating

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte, ui/components/datasetItemWorkspace/src/lib/api/objectsApi/highlightObject.ts, ui/components/datasetItemWorkspace/src/lib/api/objectsApi/scrollIntoView.ts
- Highlighting now also scrolls horizontally in the timeline
- Colored dot click is now allowed while using merge tool, highlighting is disabled but scroll into view and frame index change are allowed
- UI: More colors based on highlight state (self/all/none), and other minor improvements
=> feat(front): Highlighting and UI improvements

README.md
- Add Docker version badge
- Update coverage badge (use branch main)
- Fix pytest badge (use new GitHub action filename and use branch main instead of branch develop)
- Update badge colors
=> feat: Update README badges

README.md, docs/getting_started/creating_a_dataset.md, docs/getting_started/index.md, docs/getting_started/key_concepts.md, docs/tutorials/dataset.md, docs/tutorials/index.md, docs/tutorials/interactive_segmentation.md, docs/tutorials/semantic_search.md, mkdocs.yml, pixano/datasets/dataset_schema.py, pixano/features/schemas/annotations/info_extraction.py, pixano/features/schemas/annotations/text_generation.py, pixano/features/schemas/views/image.py, pixano/inference/zero_shot_detection.py
- Update tutorials documentation
- Update tutorials files, section titles, section levels and content for consistency
- Update getting started documentation 
- Fix the key concepts section levels and list indentations
- Split the information on creating a dataset from the key concepts to a separate dedicated page, and a link to the more complete dataset tutorial
- Fix type hints and docstrings based on warnings from mkdocs
- Update README
- Update header with the added support for text and video
- Update section titles
- Fix outdated documentation links
- Add Docker installation method
=> feat(docs): Update documentation and README

ui/components/canvas2d/src/components/TextSpansContent.svelte
ObjectCard shows one "mention" line per TextSpan, although mention could be the same.
Filter display by unique mention
=> filter unique mentions

docs/tutorials/semantic_search.md
Fix & update documentation about semantic search
=> update semantic search documentation

ui/components/canvas2d/src/Canvas2D.svelte, ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte, ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
Add a slider between DatasetItemViewer (aka Canvas) and ObjectInspector
this slider can be dragged, or clicked (click = close / reset to original size)
=> object inspector slider

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
=> fix(front): Fix number of objects visible on frame

ui/apps/pixano/src/components/dataset/DatasetBrowserForm.svelte, ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte, ui/apps/pixano/src/components/dataset/filterTable.svelte, ui/components/table/src/Table.svelte, ui/components/table/tsconfig.json
Filter UI is not at its right place inside table column header
Move it in the "DatasetBrowserForm", next to semantic search
=> Move filter into datasetbrowser form

ui/components/core/src/assets/lucide_keypoints_icon.svg, ui/components/core/src/assets/lucide_polygon_icon.svg, ui/components/datasetItemWorkspace/src/components/Inspector/ChildCard.svelte, ui/components/datasetItemWorkspace/src/components/Toolbar.svelte, ui/components/datasetItemWorkspace/src/components/Toolbar/KeyPointsSelectionTool.svelte
New icons for keypoints and polygon
=> new icons for keypoints & polygon

ui/components/datasetItemWorkspace/src/components/Inspector/ChildCard.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte, ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
Several minor bugs associated to video inspector and object inspector
bugs:
- with delete if several objects under same frame&view
- reactivity of the edit button
- edit from video inspector does not respect selected view
Fixes #535
=> keyframe & other bugs

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
A filter for confidence (for bounding boxes only) was present but disappeared in some version.
We want it back
Add a slider for confidence threshold under a "Filter" icon button
Note: the threshold is currently not persitant (not in a store) so is reset on datasetItem change. This could be changed if requested.
=> add a confidence threshold slider

docs/tutorials/index.md, docs/tutorials/pre_annotation.md, mkdocs.yml
Add a pre-annotation tutorial, showing how to pre annotate a Pixano Dataset with YOLOv11 and GroundingDINO (using Pixano Inference for the last one)
=> add pre-annotation tutorial

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
features_values.json proposed values are not managed for "annotations" group
Manage them.
Note: this still need a real rework to map back json format. (cf #491  )
=> allow features values (predefined) for Annotation

ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte, ui/components/core/src/components/ui/molecules/TooltipIconButton.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte, ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts, ui/components/datasetItemWorkspace/src/lib/api/objectsApi/addOrUpdateSaveItem.ts
=> cosmetics changes

ui/components/core/src/api/getItemsInfo.ts
unwanted redirection for items_info with ids
add a '/' to avoid redirection
=> add '/' to avoid redirect

ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte, ui/components/datasetItemWorkspace/src/components/Inspector/OptionsAndFilters.svelte
After PR #585 (TableCounts), an optional parameter has been add to getItemsInfo
This lead to a mismatch with another optional parameter
Fixed
=> minor various fixes
