pixano/pixano

CHANGELOG.md
README.md
notebooks/datasets/export_dataset.ipynb
notebooks/datasets/import_dataset.ipynb
notebooks/datasets/template_importer.py
notebooks/models/interactive_annotation.ipynb
pixano/api/items.py
pixano/apps/main.py
pixano/core/image.py
pixano/data/exporters/coco_exporter.py
pixano/data/importers/coco_importer.py
pixano/data/importers/dota_importer.py
pixano/data/importers/image_importer.py
pixano/data/importers/importer.py
tests/apps/test_main.py
tests/data/importers/test_coco_importer.py
tests/data/importers/test_dota_importer.py
tests/data/importers/test_image_importer.py
tests/data/test_dataset.py
ui/apps/annotator/src/AnnotationWorkspace.svelte
ui/apps/annotator/vite.config.ts
ui/apps/explorer/vite.config.ts
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/core/src/interfaces.ts
ui/tools/storybook/stories/apps/annotator/AnnotationWorkspace.stories.ts
ui/tools/storybook/stories/apps/explorer/ExplorationWorkspace.stories.ts
ui/tools/storybook/stories/components/canvas2d/Canvas2D.stories.ts
ui/tools/storybook/stories/components/canvas2d/LabelPanel.stories.ts

- **Breaking:** Send media files as URI instead of base 64 encodings in Pixano API. Allows for better speed and flexibility for more complex dataset, but drops support for datasets imported without copying media files (`portable=False`)
- Remove the `portable=False` option from importers. Instead users can choose to either **copy or move the media files** to the dataset directory

feat(api)!: Send media files as URI instead of base 64 encodings

---

CHANGELOG.md
pixano/data/importers/coco_importer.py

The category_name field does not always exist in an annotation object.

fix(back): Fix getting category name in COCO Importer

---

ui/apps/annotator/src/AnnotationWorkspace.svelte
ui/apps/annotator/src/App.svelte
ui/apps/explorer/src/App.svelte

In some cases, item ids can contains characters (ex: # / ?) that we must encode before passing them to REST api

encodeUri component subject to unallowed chars

---

CHANGELOG.md
docs/user/launch.md
pixano/apps/main.py
pixano/core/image.py
pixano/data/dataset/dataset.py
pixano/data/dataset/dataset_info.py
pixano/data/dataset/dataset_stat.py
pixano/data/item/item_view.py
pixano/data/settings.py
pyproject.toml

Add support for datasets on S3 cloud storage using the following settings:
- `data_dir` as an `S3Path` instead of a regular `Path` 
- `aws_endpoint`: S3 Endpoint
- `aws_access_key_id`: S3 Access key
- `aws_secret_access_key`: S3 Secret key
- `aws_region`: S3 Region
- `local_model_dir`: Local path to models directory when using S3
- Add support for S3 datasets in API
- Add support for S3 files in Dataset, DatasetInfo, DatasetStats, and Image

feat(api): Add support for S3 datasets

---

ui/components/canvas2d/src/components/PolygonGroup.svelte

fix: pixano/pixano-project-manager#35
first dot of a polygon is now 1.5 bigger than other points. It is also purple (vs green) to highlight it better.

feat(front): Improve visibility of first point of a polygon

---

.github/workflows/test.yml
notebooks/models/pre_annotation.ipynb
pixano/models/inference_model.py

Fixes pixano/pixano-project-manager#19
**Warning:** As Pixano 0.5.0b1 introduces breaking changes, in GitHub action `test.yml`, Pixano Inference is explicitly set to the matching 0.3.0b1 for Python unit tests to pass. This should be removed once the stable versions of Pixano 0.5.0 and Pixano Inference 0.3.0 are released.

feat: Update InferenceModel and pixano-inference

---

ui/components/canvas2d/src/components/PolygonGroup.svelte

**bug description**:  when a polygon is being created and the user wants to drag a point to modify the new shape, the modification gets canceled once a new point is added. 
This fixes the issue

fix(front): Keep modified points when creating a polygon

---

.github/workflows/format.yml
pixano/data/dataset/dataset.py
pixano/data/exporters/coco_exporter.py
pixano/data/importers/coco_importer.py
pixano/data/item/item_object.py
pixano/models/inference_model.py

A new stable release of the black formatter has been released (24), which breaks the backend formatting GitHub action on the latest commit to develop (2d72d37ab7a2f08a7648410e18250eb20105a7b0) as our code is formatted with version 23.
- Fix backend code formatting to be in line with version 24 of black
- Specify version 24 of black in the GitHub action to prevent this from happening with future releases of black
For those working on the backend (@BertrandRenault), update your black formatter to version 24 as well:
```bash
pip install --upgrade black~=24.1.0
```

fix(back): Fix formatting for new stable version of black

---

ui/components/canvas2d/src/Canvas2D.svelte
ui/components/canvas2d/src/api/boundingBoxesApi.ts
ui/components/canvas2d/src/components/CreatePolygon.svelte
ui/components/canvas2d/src/components/PolygonGroup.svelte
ui/components/canvas2d/src/components/PolygonPoints.svelte
ui/components/core/src/lib/types/objectTypes.ts

fixes : #59 and pixano/pixano-project-manager#15 (duplicates).
Also fixes a bug found during development : we could not edit a mask (polygon). 
Description : 
- refactor code to seperate polygon already created and the polygon being created. It helps keeping code simple. 
- Use `<Line />`component to create polygon and allow concave polygons

feat(front): Create concave polygons

---

ui/components/canvas2d/src/api/boundingBoxesApi.ts

fixes #62 
Rectangle are now draggable when edit mode is on.
New position is saved when user saves.

feat(front): Allow dragging rectangle when edit mode is on

---

pixano/core/__init__.py
pixano/core/depth_image.py
pixano/core/utils.py
tests/core/test_bbox.py
tests/core/test_camera.py
tests/core/test_depth_image.py
tests/core/test_gt_info.py
tests/core/test_image.py
tests/core/test_utils.py

- Fix DepthImage display method and existing unit tests
- Add missing BBox unit tests
- Add missing Image unit tests
- Add is_binary unit test
- Add Camera and GtInfo unit tests
Only missing unit tests in pixano.core now are:
- `Image.complete_uri`: assertRaises does not count in code coverage for some reason
- `Image.open()`: Missing test for S3 image, should be doable with [getmoto/moto](https://github.com/getmoto/moto)
- `pixano_type.py`: Testing `convert_field()` and `create_pyarrow_type()` will require some work and deserves its own issue / PR
This PR also removes the deprecated `pyarrow_array_from_list()` function from pixano.core as it is no longer used anywhere.

feat(tests): Improve pixano.core unit tests

---

ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
ui/apps/pixano/src/lib/stores/datasetStores.ts
ui/apps/pixano/src/lib/types/pixanoTypes.ts
ui/apps/pixano/src/routes/+layout.svelte
ui/apps/pixano/src/routes/[dataset]/dashboard/+page.svelte
ui/components/canvas2d/src/api/boundingBoxesApi.ts
ui/components/canvas2d/src/components/CreatePolygon.svelte
ui/components/core/src/api.ts
ui/components/core/src/lib/types/datasetTypes.ts
ui/components/core/src/lib/types/objectTypes.ts
ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte
ui/components/imageWorkspace/src/lib/api/objectsApi.ts
ui/components/table/src/Table.svelte

fixes : #72 
description : 
- BUG FIXING : reset search when arriving on a dataset table page (which was causing the bug) 
- RELATED IMPROVEMENT : display error message when search is in error 
- RELATED IMPROVEMENT : fetch dataset items only once

fix(front): Reset search when changing dataset

---

.github/workflows/.pylintrc
notebooks/models/pre_annotation.ipynb
pixano/models/inference_model.py
ui/.prettierrc.cjs
ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte

Fixes #90 
- Add option in pre-annotation notebook to save annotations as "Pre-annotation" or "Model run"
- The `process_type` argument in `InferenceModel.process_dataset()` is now split from `"obj"` to either `"pre_ann"` or `"model_run"` to let the user choose if they want the generated annotations to appear as "Pre-annotation" or "Model run" in the app.
- The pre-annotation notebook is also updated to reflect this new choice.
- Update "Ignore" pre-annotation button to "Reject" in the app
- As discussed during the latest sprint demo (Fri 02/02/2024), "Reject" makes more sense for the end users, and better reflects the fact that the annotation will not be shown again.
- This update also improves consistency with new documentation in inference_model.py and pre_annotation.ipynb describing …

feat(back): Choose Pre-annotation or Model run in InferenceModel

---

pixano/data/item/item_object.py
ui/components/imageWorkspace/src/components/ActionsTabs/ObjectTabFlatItem.svelte
ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte

Part 1/2 of issue #89 
- Fix creating bounding box from mask automatically
- Create bounding box from mask when saving an object without needing to create an empty box in the frontend first. This fixes the issue where the empty box would be displayed on the image while it shouldn't.

fix(api): Create bounding box from mask automatically

---

notebooks/models/pre_annotation.ipynb
pixano/models/inference_model.py
ui/.prettierrc.cjs
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte

Remove construction inputs after validation/cancel
Also allow "Escape" key along with cancel button
close #88

feat(front): remove inputs after validation/cancel

---

notebooks/models/pre_annotation.ipynb
pixano/data/item/item_embedding.py
pixano/data/settings.py
pixano/models/inference_model.py
ui/.prettierrc.cjs
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/core/src/utils.ts
ui/components/imageWorkspace/src/components/PreAnnotation/PreAnnotation.svelte

Fixes #95
- AWS_ENDPOINT and AWS_REGION are required by lancedb for S3, AWS_ENDPOINT was previously renamed to ENDPOINT_URL.
- URL images were not correctly handled

fix: S3 and URL wrongly handled

---

ui/components/imageWorkspace/src/components/ImageInspector/ObjectsInspector.svelte

#101 
I could not display the number of object included in a model since it was deleted

fix(front): Allow zero to be shown in model run number of object

---

ui/components/imageWorkspace/src/components/Toolbar.svelte
ui/components/imageWorkspace/src/lib/settings/selectionTools.ts

Fixes #114
- Add missing tooltip for the bounding box and smart tool list buttons
- Fix existing tooltips for the other tools
- Use the `SelectionTool.name` as `tooltipContent` for all buttons
- Fix a typo: `polygoneTool` > `polygonTool`
- Redefine the smart tool list button with IconButton
- IconButton allows the smart tool list button to use `tooltipContent` like the other buttons
- `on:dblclick` is not implemented in IconButton. Show the model selection modal every time the smart tool list is opened instead. Closing and re-opening the smart tool list works similarly to double clicking.

fix(front): Fix buttons in Toolbar

---

ui/components/imageWorkspace/src/components/ImageInspector/ObjectCard.svelte
ui/components/imageWorkspace/src/components/ImageInspector/ObjectsModelSection.svelte
ui/components/imageWorkspace/src/components/ImageInspector/SceneInspector.svelte

Fixes #116 
- Open object card when clicking on editing button (since as of #87, object cards are closed by default)
- Add missing button tooltips (scene features, object visibility, object highlighting, object card toggle, bounding box and mask toggles)
- Fix existing button tooltips consistency (first letter should be uppercase)

fix(front): Fix buttons in ImageInspector

---

ui/apps/pixano/src/components/layout/DatasetHeader.svelte

Fixes #119
- Add missing tooltips for back button and dataset navigation buttons
- Make back button go to the parent page (home page if on dataset page, dataset page if on item page), instead of behaving like the Pixano logo button

fix(front): Fix buttons in DatasetHeader

---

ui/components/canvas2d/src/Canvas2D.svelte
ui/components/imageWorkspace/src/components/LoadModelModal.svelte
ui/components/imageWorkspace/src/lib/api/modelsApi.ts

Fixes #123 
- Throw error in `modelsApi` if empty embeddings received to trigger the "No embeddings found for model" modal
- Fix updating the `currentModalOpen` variable that would trigger the "No embeddings found for model" modal even after switching model
- Add details to the "No embeddings found for view" modal that can trigger if clicking too quickly after selecting a model, because the embeddings have not yet finished loading

fix(front): Fix issues with loading segmentation models

---

ui/components/canvas2d/src/Canvas2D.svelte
ui/components/canvas2d/src/components/PolygonGroup.svelte
ui/components/canvas2d/src/components/PolygonPoints.svelte
ui/components/canvas2d/src/components/Rectangle.svelte

fixes #112 
Users can now only select object by double clicking them when the PAN tool is activated to avoid conflict with shape creation.

fix(front): Only allow object selection when PAN tool is activated

---

ui/components/imageWorkspace/src/components/Features/FeatureFormInputs.svelte

Fixes #113 
For some reason that I can't explain, `autofocus={false}` was not working, leading to warning in browser console and the last input being indeed focused. 
The fix is not DRY but the only way I could find to make it work.

fix(front): Autofocus only the first input in Feature Form

---

ui/components/imageWorkspace/src/lib/api/objectsApi.ts

fixes #128
small changes, big impact here. 
editing a polygon was mutating the wrong object because I was not checking for the ID to mutate.

fix(front): Do not mutate object if id does not match

---

ui/components/canvas2d/src/Canvas2D.svelte
ui/components/canvas2d/src/components/Rectangle.svelte
ui/components/imageWorkspace/src/components/SaveShape/SaveShapeForm.svelte

fix(front): reshape bbox with positive height/width

---

pixano/app/serve.py

fix(back): correct AWS env var name

---

.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.gitignore
ui/pnpm-lock.yaml

fixes #97 
Instead of locking manually package version, I've added a flag `--frozen-lockfile` to GH actions. 
According the [docs](https://docs.npmjs.com/cli/v10/commands/npm-ci) this should have been the case since the command was run in CI already. So maybe there is something we did wrong or `CI=TRUE` was not explicit enough? 
`--frozen-lockfile` flag is [equivalent](https://stackoverflow.com/questions/70154568/pnpm-equivalent-command-for-npm-ci) to `npm ci` : https://docs.npmjs.com/cli/v10/commands/npm-ci

chore: Freaze lockfile in CI

---

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
ui/components/canvas2d/src/api/rectangleApi.ts
ui/components/canvas2d/src/components/Rectangle.svelte

Fixes #147 
The `transformer` is the Konva object that allow modifying shape.
When a rectangle is destroyed (removed from the DOM), it is always removed from the `Transformer`

fix(front): Do not add random transform shape after deleting an object

---

ui/components/imageWorkspace/src/components/LoadModelModal.svelte

fix(front): Add explicit "none" model selection when no embeddings

---

ui/components/core/src/components/ui/input/input.svelte
ui/components/core/src/index.ts
ui/components/datasetItemWorkspace/src/components/Features/AutoCompleteFeatureInput.svelte
ui/components/datasetItemWorkspace/src/components/Features/TextFeatureInput.svelte
ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte

Fixes #159 and #157
- Reverted to a popover to display the feature list of the autocomplete feature as it allows placing the list on top of the app. 
- The combobox opens either on click or on keypress "enter" for keyboard users. I believe the UX is still performant.
- Fixes tiny layout alignments 
- For now, when the user input a new value, it can be selected. All "intermediate" values are temporary saved. Eg. If I input "Balloon", "B", "Ba", "Ball"... "Balloon" will be temporary saved. It is only visible if the user erases its input. Once its closed, only the final input is saved. I decided it was ok and not to lose more time on this. I can improve that behavior if you think I should.

fix(front): Improve autocomplete UX and placement

---

pixano/app/serve.py

Fixes #158
Solution found with the help of @timothee-LJN!
Adding individual endpoints for each frontend route allows refreshing the page without "Not found" errors, and keeps the current route.
Currently, only three routes exists outside of the already functional home page: the dataset page, the dashboard page, and the item page. If new routes are added in the frontend, they will need to be added in the backend server as well.

fix(api): Allow refreshing the deployed app

---

ui/apps/pixano/src/routes/+layout.svelte

Fixes #174
Fix inconsistent background color at the bottom of the home page

fix(front): Fix home page background color

---

ui/apps/pixano/src/app.html

Fixes #149
Add empty favicon in HTML file to disable 404 error in deployed app. Favicon from Svelte file still loads correctly.

fix(front): Fix favicon 404 error

---

ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte

Fixes #178 
Reactivity in `<PreAnnotation />`component was causing an unwanted update of all objects. It was intended to be only if pre-annotation was active.

fix(front): Update object in preannotation only if its active

---

pixano/models/inference_model.py

Fixes #168
inference_model > _load_rows() doesn't rely on table order anymore
This PR is draft, for reference, as _load_rows() should use methods from Dataset class, which may depends on RFC1 [rfcs/RFC1.md](https://github.com/pixano/pixano-project-manager/blob/main/rfcs/RFC1.md)

fix(back): inference_model: don't rely on db/media table order

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
ui/components/datasetItemWorkspace/src/components/PreAnnotation/PreAnnotation.svelte
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

Fixes #156 
- Put preAnnotationIsActive in store
- prevent unwanted update of itemObjects when in pre-annotation mode
Also, remove annoying autofocus on feature input(s) in pre-annotation mode

fix(front): Fix Objects disappear on click in pre-annotation mode

---

ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

Fixes #189 
- add `selectedTool` to `DatasetItemWorkspaceStore` 
- use PAN when switching to edit mode

fix(front): Use pan tool when editing object

---

.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/test.yml

Fixes #191
Replace deprecated Node.js 16 actions as GitHub's complete transition to Node.js 20 actions is expected for spring 2024.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

fix(ci): Update deprecated actions

---

.github/workflows/publish.yml

Fixes #193
Use PyPI trusted publishing instead of API tokens

feat(ci): Use PyPI trusted publishing

---

.github/workflows/lint.yml
.github/workflows/test.yml

Fixes #196
GPU support with CUDA is not necessary for linting and testing Pixano, so skipping CUDA installation by installing the CPU versions of PyTorch and TensorFlow reduces the actions run time by a minute or so.

fix(ci): Prevent CUDA installation in lint and test actions

---

CHANGELOG.md
pixano/data/exporters/coco_exporter.py

Fixes #201
Since the `categories` field of `DatasetInfo` is optional, it can be null when using `ImageImporter`.
`COCOExporter` should thus check if the field is null before trying to iterate on it.

fix(back): Check if categories field to export is not null

---

pixano/data/dataset/dataset.py
ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/Features/TextFeatureInput.svelte
ui/components/datasetItemWorkspace/src/lib/api/featuresApi.ts

- List of existing values was incorrectly retrieved from tables when several tables present (last erased previous values)
- When no features_values set, some bugs with unset values
- Correctly handle available values from different tables
- Protection against undefined values

fix(front&back): featuresList bugs

---

ui/components/canvas2d/src/components/CreateRectangle.svelte

Fixes #209 
In the new `<CreateRectangle />` component, a check is done to verify that viewIds match

fix: Check viewId in rectangle creation to avoid multiview box duplication 

---

pixano/data/exporters/coco_exporter.py

Fixes #221 
Add a missing protection when "supercategory" field has not been filled (because no "supercategory" info in dataset)

fix(back): missing protection on no supercategory to export

---

pixano/data/dataset/dataset.py

Fixes #227 
Add protection to not merge when empty table
Add review_state internal field when creating table --> this should probably be reworked with python API and custom schemas

feat(back): protection against empty table and default review_state

---

ui/components/canvas2d/src/Canvas2D.svelte

Fixes #229 
input rectangle for segmentation is not created under "input" group anymore (since #205 )
So we find it by it's name "drag-rect" now

fix(front): look for input rect in drag-rect instead of input

---

docs/restAPI_reference/data_items.md
ui/components/canvas2d/src/components/Thumbnail.svelte
ui/components/core/src/api.ts
ui/components/core/src/lib/types/datasetTypes.ts
ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts

Fixes #244 
- thumbnails are not displayed on track hover
- thumbnails are displayed on scene inspector
- object being highlighted are open in inspector (but not closed, this could be change. Any mind?) 
- by default, the thumbnail is the first frame of the track is used for the thumbnail. User cannot change that for now but I changed the data structure to save it in the database. Documentation has been updated. Maybe this could be simplified. What do you think @BertrandRenault ?
- it only works for videos now, shall we do it for images as well @jrabary ?

feat: show thumbnail on editor

---

pixano/app/api/items.py
ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
ui/components/core/src/api.ts
ui/components/core/src/lib/types/datasetTypes.ts
ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyBox.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts
ui/tools/storybook/stories/components/workspaces/videoDatasetPayload.ts

For SequenceFrame, tracks:
keypoints was arbitrarily set to be first and last object of each tracklet.
Now keypoints info is stored in object (TrackObject) as a flag "is_key"
Also, renamed "keyBoxes" to "boxes"
TODO (other PR/commit): put TrackObject in Pixano types

fix(back): add is_key & rename keyBoxes to boxes

---

pixano/datasets/features/__init__.py
pixano/datasets/features/schemas/track_object.py

TrackObject (TrackObjectWithBBox, TrackObjectWithMask, TrackObjectWithBBoxAndMask) must be native Pixano types as their fields are required
TrackObject classes in pixano.datasets.features.schemas

feat(back): track_objet native class

---

pixano/datasets/features/types/bbox.py
pixano/datasets/features/types/bbox3d.py
pixano/datasets/features/types/camcalibration.py
pixano/datasets/features/types/compressed_rle.py
pixano/datasets/features/types/keypoints.py
pixano/datasets/features/types/nd_array_float.py

LanceDB doesn't allows null values. (It should with Lance V2 format planned for september)
So in the meanwhile, we use empty types that we must detect/interpret as null values
Each Pixano base type has a "none()" static function to create this empty type, for convenience

None predefined types

---

pixano/datasets/features/__init__.py
pixano/datasets/features/schemas/object.py
pixano/datasets/features/schemas/track_object.py
pixano/datasets/features/types/bbox.py
pixano/datasets/features/types/compressed_rle.py

Now that we can use "empty objects" to fake null values, we can avoid using ObjectWithBBox, ObjectWithMask, ...
We use Object, that has bbox and mask (and everything we could put), with empty values by default when not needed
Idem for TrackObject

feat(back): simplify Object and TrackObject

---

pixano/app/api/items.py
pixano/datasets/builders/dataset_builder.py

Need to be more flexible for builders, to yield data as it goes.
- Allow to provide "incomplete" data (not all DatasetItem tables provided)
- Some additional checks on data and error management
- Corrected a check for media type (image/video) that could be wrong because Image is a subclass of SequenceFrame
- Manage timestep AND/OR timestamp for tracklets (there was only timestep)
- Add a check for track_id == '-1', that is often used to mark "broken" data, in order to skip it. **THIS CHECK IS SUBJECT TO REMOVAL**

fix(back): better management of some data errors/specific cases

---

ui/components/canvas2d/src/components/CreateKeypoints.svelte

Fixes #280 
When adding keypoints to the canvas, the background is now fitted around the keypoints.

feat(front): fix keypoints background position

---

ui/components/canvas2d/src/Canvas2D.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

Fixes #277 
Added an image smoothing toggle to improve the accuracy of visual representation for tasks that require precise pixel-level annotations.
The toggle can be found in the Scene tab of the inspector, it is enabled by default.

feat(front) : Add an image smoothing toggle in settings

---

pixano/app/api/items.py

Right now, front can't manage "dynamic" metadata (video).
For now, we manage only static metadata (track level)
Do not send annotation and sub-entities metadata to front

limit objects features to top level entity

---

pixano/app/api/items.py
pixano/datasets/dataset.py
pixano/datasets/features/schemas/annotations/camcalibration.py
ui/apps/pixano/src/components/layout/DatasetHeader.svelte
ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/canvas2d/src/components/Rectangle.svelte
ui/components/canvas2d/src/components/ShowKeypoint.svelte
ui/components/core/src/api.ts
ui/components/core/src/lib/types/datasetTypes.ts
ui/components/core/src/lib/types/objectTypes.ts
ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi.ts
ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
ui/components/datasetItemWorkspace/src/lib/settings/defaultFeatures.ts
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
ui/components/models/package.json
ui/components/models/src/Sam.ts
ui/pnpm-lock.yaml
ui/tools/storybook/stories/components/workspaces/datasetItemWorkspaceMocks.ts

Save was disabled since Python API refactor
It's now working (but should be further tested)
Changed the way save is handled: from a complete DatasetItem sent to back, it's now a list of changes, handled by back
Also:
- guard against refresh without save
- various fixes/changes in trackline UI
TODO:
TOFIX - trackline bugs:

front save rework

---

pixano/app/routers/items_info.py
pixano/app/routers/utils.py
pixano/datasets/builders/dataset_builder.py
pixano/datasets/dataset.py
pixano/datasets/utils/__init__.py
pixano/datasets/utils/errors.py
pixano/datasets/utils/integrity.py
tests/app/routers/test_utils.py
tests/conftest.py
tests/datasets/builders/test_dataset_builder.py
tests/datasets/test_dataset.py
tests/datasets/utils/test_integrity.py
tests/fixtures/app/routers/models/annotations.py
tests/fixtures/datasets/builders/builder.py
tests/fixtures/datasets/dataset.py
tests/fixtures/features/entity.py

Add integrity checks for:
- analysing a dataset
- analysing a table
- adding or updating data
Integrity checks can be performed when building the dataset.

Add integrity checks

---

.github/workflows/docker.yml
.github/workflows/update_versions.yml

Prevent docker workflow to launch every time
update_version launch for PR only and not push on main that is protected

Prevent docker workflow to launch every time, fix update_version for PR only

---

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
ui/components/core/src/api.ts

Deleting multiple items is managed item by item.
When we delete a whole track, it's too much REST API calls
We take advantage of the route that accept a list of ids instead of multiple call to the single id route,
by grouping ids to delete by group and table

Grouped deletion

---

pixano/app/routers/browser.py
pixano/datasets/dataset.py
tests/datasets/test_dataset.py

Move semantic search logic from REST API to dataset so one can perform it either via the Python API or the REST API.

Refactor semantic search in Dataset

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte

Images were loaded on demand. This could slow down the play of video
Asynchronously, load and store each frame as HTMLImageElement (almost ready to display), populating the buffer frame by frame (across views)
Note: 
pro: faster play when frame loaded, populating asynchronously so very little overhead cost.
con: all calls to API for views at the start, all frames are loaded even if we just want a quick view on the item.

add a frame buffer for faster play

---

ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts

Previous implementation of getCurrentImageTime() displays both "0:60" then "1:00" when passing from one minute to the next

fix(front): Fix getCurrentImageTime()

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte

Pixano app do not have a max size for media buffer, leading to crash (memory full)
Fixes #366 
Implement a circular buffer (actually 50 frames after and 5 frames before current frame)
-- this settings are currently hard coded
tech detail: the 50 next (including current) and 5 previous are loaded at start, and each time we change current frame index. If any of the required buffer frames are not present, load it. frmaes outside of this range are removed from buffer, so it always have a size of 55 frames ( * nb views) --- please note that we add before deleting, so at max we can have 55 * 2 images in the buffer. -- in usual cases (play or step forward/backward), only one frame is added / removed each time

circular buffer

---

pixano/app/routers/browser.py
pixano/features/utils/image.py
tests/features/utils/test_image.py

When an image is read, sometimes the format is lost and base64 couldn't convert on its own.
In this PR we allow base64 to receive a format  to allow conversion.

Fix base64 conversion when format is None

---

pixano/features/utils/image.py
tests/features/utils/test_image.py

image_to_base64 will crash with a "Unknown" image format.
It happens sometimes (I had it with one dataset. Images are .jpg but for it seems PIL doesn't correctly identify the format, although he can read it)
If format is "Unknown", use "JPEG" instead. As it is an internal save before base64 encoding, for thumbnail, this has no impact.

bugfix unknown image type

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte

At 5 or more views, the tracklet size is too small (track size / n views) in videoInspector to interact with (and currentFrameIndex is not set also because of a reactive component being disabled because too small, which leaded to several bugs)
Fix #378 
The tracklet now have a fixed size, and the track have a variable size depending on number of views.

fixed tracklet size

---

ui/components/datasetItemWorkspace/src/lib/api/videoApi.ts
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

With sub entities, the color for annotation may be wrong
- ColorScale now based on top entities only, (not all entities including sub entities)
- top entities were removed from interpolated annotations. It's fixed

fix colorScale with sub entities

---

ui/components/core/src/utils.ts

Replace the existing schemeSet3 color palette (12 colors) with a new custom color palette (32 colors)
Created a larger color palette using https://mokole.com/palette.html to have more visually distinct colors.

feat: Add larger color palette

---

pixano/features/schemas/views/image.py
tests/features/schemas/views/test_image.py

Add a util function in Image to shorten their url , for easier dataset building.
This helps the creation of a dataset where Image object are created with known dimensions format 
and theorical path, but when images are not yet accessible (only remote, or under credentials,
in a private network, etc).
This can also help to fix properly image url to relative path after an eager usage of create_image() .

feat: add util funct in Image to shorten url wrt relative path

---

ui/apps/pixano/src/routes/[dataset]/dataset/[itemId]/+page.svelte
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/canvas2d/src/components/PolygonGroup.svelte
ui/components/canvas2d/src/components/Rectangle.svelte
ui/components/canvas2d/src/tools.ts
ui/components/core/src/lib/types/toolsTypes.ts
ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar/FusionTool.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar/KeyPointsSelectionTool.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedEntity.ts
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineCreatedObject.ts
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/getPixanoSource.ts
ui/components/datasetItemWorkspace/src/lib/settings/selectionTools.ts
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts
ui/components/datasetItemWorkspace/src/lib/types/datasetItemWorkspaceTypes.ts

For video, we want to be able to merge tracks (Re ID)
Fixes #379 
Also should fixes #389 
New feature: 
use the "Associate" button to enter *Association* mode.
click on bbox in views to add their whole track to the association list. Click on an already selected bbox to remove it from list.
The first one clicked is the reference (all will be merged in this one). -- first in the list at validation time, it could have changed if first has been deselected
Click "Validate" button to merge. (it doesn't save, you have to save as usual to push changes to back).
Click "Abort" button to cancel current association.
+ some minor code refactoring on ToolType (use Enum ToolType instead of plain string)
+ fix for trailing Z in dates (see #389)
+ add track label "name (id)" in video inspector
Note: only …

track association

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte

Better scaling of markers and time indicators for longer videos with more granular options based on timeline density
Note: time indicators in "`{mm}`:`{ss}`" format for videos longer than a minute, and in "`{ss}`s" for shorter videos

feat(front): Better TimeTrack scaling

---

ui/components/datasetItemWorkspace/src/DatasetItemWorkspace.svelte

Partial solution for #372 while waiting for a more thorough implementation
Replace the default video speed value of 100 ms (10 fps) with actual video speed, computed by dividing the video length (end timestamp - start timetamp) by the number of frames

feat(front): Estimate video speed

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte

Rare case scenario, but if the `end_timestep` of a tracklet is equal to the `start_timestep` (i.e. tracklet consisting of a single frame), have a minimum width of 1 frame. Otherwise the tracklet is invisible in the timeline.

fix(front): Add a minimum tracklet width

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte

Rare case scenario, but when deleting a tracklet, there can be other empty tracks than its parent (maybe because of a problem during import, or an issue with a previous save).
Delete all existing empty tracks rather than just the first one that is found.

fix(front): Delete all empty tracks

---

ui/components/core/src/components/ui/slider/SliderRoot.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoInspector.svelte

Just a small UI improvement to add zoom in and zoom out icons on each side of the zoom slider for the video timeline, based on a suggestion that its purpose might not be obvious for all beginner users.

feat(front): Add icons for timeline zoom slider

---

ui/components/canvas2d/src/components/Thumbnail.svelte
ui/components/core/src/lib/types/dataset/datasetTypes.ts
ui/components/datasetItemWorkspace/src/components/Features/CreateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/DisplayCheckbox.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/SceneInspector.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineObjectThumbnail.ts

-  Select better bounding boxes for object thumbnails
-  Take the bounding box of the middle of the track for each view, which will better show the object than the first bounding box (often smaller or partial view).
- Add object thumbnails for each view for multi-camera tracks
- Fix thumbnails dimension and aspect ratio calculations
- Change minimum and maximum dimensions of object thumbnails
Tested on multi-view video datasets and single-view image datasets

feat(front): Update object thumbnails in side panel

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte

When using SAM, user doesn't know when embeddings are loaded, and often get a modal saying "embeddings not loaded yet". 
A Loading icon would be appreciated
Add a loading icon while embeddings are not loaded

add loading icon when loading embeddings

---

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte

When a dataset has sub-entities, the highlighted thumbnail shown in right panel are incorrectly taken from each sub entities.
Use getTopEntity instead of just relying on parent entity (which is the sub entity if exist)

fix highlighted selected entity when sub entities

---

ui/components/table/src/Table.svelte
ui/components/table/src/TableCell.ts
ui/components/table/src/TableCells/DateTimeCell.svelte

- Table
- Change names like "created_at" and "updated_at" to "created at" and "updated at" for more readable columns
- TableCell
- Add DateTimeCell to display datetime values like created_at and updated_at in a more human readable format

feat(front): Small dataset page enhancements

---

ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte
ui/apps/pixano/src/components/layout/MainHeader.svelte

- MainHeader
- Add plural for datasets and items on homepage only if needed
- DatasetPreviewCard
- Reduce width of title to leave space for the "Open" arrow
- Add plural for number of items only if needed
- Hide dataset size if "Unknown"

feat(front): Small homepage enhancements

---

ui/components/datasetItemWorkspace/src/components/Toolbar.svelte

After either validating or aborting the current fusion, keep the fusion tool selected so the user can keep annotating without having to select the tool again.

feat(front): Keep fusion tool selected

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/TimeTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte

Small UI enhancement.
When using the spacebar shortcut for play/pause after a click on the TimeTrack (e.g. to move the video cursor), the TimeTrack gets a black outline from being in focus, and the VideoInspector scrolls down.
Disable this unwanted black outline and scrolling.

feat(front): Disable focus and scrolling on spacebar shortcut

---

ui/components/datasetItemWorkspace/src/lib/api/objectsApi/addOrUpdateSaveItem.ts

If we have non unique id (though in different table) the process of filtering SaveItem (already modified) would bug because of "too large (in whole dataset, not just within tables)" unique id assumption.
Fixes #437 
check also for table_info when filtering saveItem by ids

SaveItem update: check with id and ALSO table_info

---

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsInspector.svelte

A source used to group entities in Object Inspector had wrong "metadata" type
Fixed

fix fake source metadata type

---

ui/components/core/src/components/modals/SelectModal.svelte
ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte

In SelectModal (used when we select a segmentation model and embeddings), when no choice is available, or if we want to abort, only a "OK" button. In some case it cause an infinite loading wheel (though nothing is loading)
- Add a Cancel button
- disable OK button is nothing is selected

add a "cancel" button to SelectModal

---

pixano/datasets/dataset_info.py
ui/apps/pixano/src/components/dataset/DatasetPreviewCard.svelte

thumbnails displayed in datasets explorer page do not resolve relative path, and so doesn't display thumbnail if library dir is given as a relative path
resolve() path to absolute

dataset thumbnail: get absolute path

---

ui/components/core/src/components/ui/autoresize-textarea/autoresize-textarea.svelte

The open answers are not saved.
Forward specifically the blur event of autoresize textarea.

fix: autoresize-textarea component by forwarding the blur event

---

pixano/datasets/workspaces/dataset_items.py
tests/datasets/builders/test_folders.py

Default VQA schema used by VqaFolderBuilder lacks tables Entity, BBox; Mask, Keypoints
Add them

add entity, bbox, ... tables to default vqa schema

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte

Add a padding of 0.5 left and right of the tracklet, so that even a single frame tracklet is visible, and is always centered on its frame index, rather than being offset to the right.

feat(front): Center tracklets in timeline

---

ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte

***Suggestion***
When editing tracklets in long videos, having the cursor move on the right click is difficult to work with, as it requires being very precise and/or zooming very closely on the tracklet to right click at the exact position. It is much easier to get to the exact position where you want to perform an action (like "Split tracklet or "Add a point") by using the video controls (Play / Pause, Previous frame, Next frame).
This commit disables changing the frame index on right click, and actions like "Split tracklet" or "Add a point" are instead performed on the current frame index if possible. If the frame index is not compatible with those actions, they are hidden.

feat(front): Disable changing frame index on right click

---

pixano/datasets/builders/folders/base.py
tests/conftest.py
tests/datasets/builders/test_folders.py
tests/fixtures/datasets/builders/folder.py

- If user add a custom metadata while using a FolderBuilder without metadata.jsonl, no default value is provided for custom metadata resulting in a pydantic validation error
Fixes #500 
- If schema contains a Conversation, without metadata.jsonl, no Conversation is created, which make impossible to add questin and so on on VQA workspace.
- Add a default value based on type of metadata
- Create a default Conversation when needed

folder default item values & default conversation

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte

In VQA and Entity Linking workspaces, SAM segmentation was not possible, because the embedding loading was made inside ImageViewer.svelte (Image workspace)
Put embedding loading outside of Imge workspace, allow it for Image, VQA and Entity linking workspace
(what about Video workspace ? -- probably not as we want tracking with SAM2 here)

allows segmentation for vqa and EL workspaces

---

ui/components/datasetItemWorkspace/src/lib/api/objectsApi/highlightObject.ts

On highlighting, if highlighted track is already visible on the current frame, no need to change and go the the first frame of track.
I thought I had already added this check but I guess not.

feat(front): Change highlight frame only if outside of track bounds

---

ui/components/textCanvas/src/lib/utils/createHtmlTags.ts

With some colors, text becomes hard to read
Compute luminance of background color to choose black or white font color

textspan: compute background luminace to choose text color

---

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte

- In ObjectCard, change text depending on number of objects. This was originally done in #507 but lost in the later commits.
- For highlighting, disable changing opacity of "none" objects outside of fusion tool:
- Making objects with highlight state equal to "none" more transparent is really only necessary in fusion tool, for objects that cannot be selected because of overlap.
For regular highlighting, this not really needed, especially now that the highlighted object is much more visible with both the updated scroll into view, and the higher opacity colors.

fix(front): Minor UI fixes

---

docs/tutorials/create_your_first_library.md
docs/tutorials/segmentation_powered_by_sam.md
pixano/datasets/builders/dataset_builder.py
pixano/datasets/builders/folders/base.py
pixano/datasets/builders/folders/video.py
tests/datasets/builders/test_folders.py
tests/fixtures/datasets/builders/folder.py

To simplify *FolderBuilder
replace previous (from documentation exemple)
```
builder = ImageFolderBuilder(
source_dir=Path("./assets/health_images"),
target_dir=Path("./pixano_library/health_dataset"),
dataset_item=HealthDatasetItem,
info=DatasetInfo(
id="health_images",
name="Health Images",
description="A dataset of health images",
),
url_prefix="/health_images"
)
```
by
```
builder = ImageFolderBuilder(
media_dir=Path("./assets"),
library_dir=Path("./pixano_library"),
dataset_item=HealthDatasetItem,
info=DatasetInfo(
id="health_images",
name="Health Images",
description="A dataset of health images",
),
dataset_path="/health_images"
)
```
- target_dir, source_dir and url_prefix removed.
- media_dir, library_dir, dataset_path add.
This way, we ask the 2 usual paths, the paths required by …

folder builder change params

---

ui/apps/pixano/src/components/library/DatasetsLibrary.svelte
ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

After a datasetItem change, or a tool change, we're asked for model & table again.
Fixes #514 
- Keep model and table while on the same dataset, do not re ask when selecting segmentation tool if already loaded (NOTE: if you loaded a bad model/table for some reasons, you need to go back to library or refresh browser to load again)
- Do not change tool while changing datasetItem
- reset tool, model and table when changing dataset (in fact when we go to library welcome page)
- also reset colorScale (to have consistant colorscale when changing dataset)

fix SAM loading model & emb table

---

.github/workflows/docs.yml

When publishing a release by updating the Pixano version, the release GitHub action tries to publish the updated documentation (with a new stable version alias), and fails as the documentation branch has already been changed by the standard documentation GitHub action that runs on every commit with a change in `pixano/**`.
Exclude `pixano/__version__.py` from the standard documentation GitHub action to prevent those conflicts.

fix(ci): Fix docs deployment conflicts

---

pixano/datasets/dataset.py
pixano/datasets/dataset_schema.py
tests/datasets/test_dataset_schema.py

If a schema already exist in schema.json, raise an error. 
It is really annoying for SAM embeddings, when something went wrong while computing them (eg. Out of memory error)
Allow shema overwrite

allow schema overwrite

---

ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte

To prevent weird capitalization like "Category Id" instead of either "ID" or "id", don't capitalize the names of object features and leave the text in lowercase, as is already done in the DatasetExplorer Table.

chore(front): Remove capitalization of names of object features

---

ui/components/textCanvas/src/TextSpanArea.svelte
ui/components/textCanvas/src/components/SpannableTextView.svelte
ui/components/textCanvas/src/lib/utils/createHtmlTags.ts
ui/components/textCanvas/src/lib/utils/textSpansToHtml.ts

With textSpan of composed words, the HTML span only take the first word (+ 1 char !)
Need to be able to select a TextSpan, and see it is selected.
- Fixed textSpan color highlight (now, it take each word (internal span) separatly, but glue them if they follow
(end[N] - start[N+1] <= 2  --> this allow 1 or two chars between two words (aka a space, or punctuation + space))
- TextSpan can now be selected in TextView (by a click) -> it highlight them (with a glow effect) ans also select the corresponding entity
- also fix line feeds (\n -> \<br>)

TextSpan enhancements

---

pixano/app/routers/browser.py
ui/apps/pixano/src/components/dataset/DatasetExplorer.svelte
ui/apps/pixano/src/components/layout/DatasetHeader.svelte
ui/apps/pixano/src/lib/stores/datasetStores.ts
ui/apps/pixano/src/lib/types/pixanoTypes.ts
ui/apps/pixano/src/routes/+layout.svelte
ui/apps/pixano/src/routes/[dataset]/dataset/+page.svelte
ui/components/core/src/api/getBrowser.ts
ui/components/core/src/api/getDatasetItemsIds.ts
ui/components/table/package.json
ui/components/table/src/Table.svelte
ui/components/table/src/filterTable.svelte
ui/pnpm-lock.yaml

Allow to filter dataset items in browser page.
A selector allows to choose a column amongst columns (restricted to string/int/float types)
An input field allows to enter the value to seek in this column (check for equality)
Typing enter in this input launch the filter
A button allows to clear the filter
A "special" free mode allows to enter a "where" clause directly (for more specific / complex / composed filter)
Also, the filtered selection is kept when navigating in dataset Item page.

Allow filtering of datasetItems on browser page

---

ui/apps/pixano/src/components/layout/DatasetHeader.svelte
ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte

When annotating (from DatasetItem view), it's convenient to know where we are in the dataset items.
Add "{index} of {num_items}"  in the header.
It take account of the current filter if any

add index of count in header

---

ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte

In a EntityLinking workspace, features edition doesn't work
In EntityLinking, entities are MultiModalEntity, and where not correctly handled by previous filter (only on Track and Entity)
Added MultiModalEntity to allowed kind of entities

feature update: missing MultiModalEntity in allowed Entities

---

pixano/datasets/builders/folders/base.py
tests/datasets/builders/test_folders.py

If "id" or "split" is in metadata.jsonl (or any genrated dict used for folder builders), _create_items raise a "TypeError: ... got multiple values for keyword argument ..."
change _create_items and calls to this function so that "id" and "split" are not parameters but already in the item_metadata dict

fix builder when id or split in metadata.jsonl

---

ui/components/textCanvas/src/components/SpannableTextView.svelte
ui/components/textCanvas/src/lib/utils/editorSelectionToTextSpan.ts
ui/components/textCanvas/src/lib/utils/textSpansToHtml.ts

Incorrect TextSpan position since a previous change
Fixes #546 
- remove incorrect "-1" for textspan length
- remove the replaceAll("\n",  "\<br>") that changed positionning, instead using "whitespace-pre-wrap" div class

fix position and avoid linefeed replace

---

ui/components/datasetItemWorkspace/src/lib/api/objectsApi/defineTooltip.ts

When there is no "display feature" ("name", "category", or "category_name" feature in entity), the confidence is not displayed
Always display confidence if != 0.0 and source != {kind: "ground_truth", name: "Pixano"}
TODO: 
it is not displayed with source {kind: "ground_truth", name: "Pixano"} --> check if it's really smart...
Also, maybe don't display if 1.0 ?
Maybe remove it from nonFeatureFields ? (but then it will be editable!)

display confidence even if no "display feature"

---

ui/components/datasetItemWorkspace/src/components/Inspector/ChildCard.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTrack.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/deleteObject.ts

Right clicking on a tracklet (in VideoInspector) while in fuison mode lose current selection.
Fixes #534 
Prevent selection of right-clicked tracklet when in fusion mode.
Manage delete in fusion mode (update "to fuse" and "forbidden" lists)
Also, removed ability to relink & glue while in fusion mode, as it could create confusion with the current "to_fuse" selection.
@cpvannier In fact I should also probably remove split, as it also may create buggy cases. Another option is to limit split & glue to tracks outside of the ones selected for fusion, but it may change the forbidden list too, so need a specific manangement. I think it's better to just disallow them. (For relink, it's too confusing to relink while fusing -- which is the same thing in fact).
@cpvannier Another note: the relink …

do not select tracklet on right click when fusion

---

pixano/app/routers/inference/__init__.py
pixano/app/routers/inference/mask_generation.py
pixano/inference/mask_generation.py
tests/app/routers/test_inference/test_mask_generation.py
ui/apps/pixano/src/lib/stores/datasetStores.ts
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/core/src/api/inference/listModels.ts
ui/components/core/src/components/pixano_inference_segmentation/AddModelModal.svelte
ui/components/core/src/components/pixano_inference_segmentation/ConnectModal.svelte
ui/components/core/src/components/pixano_inference_segmentation/ModelItem.svelte
ui/components/core/src/components/pixano_inference_segmentation/SelectLocalOrDistantModelModal.svelte
ui/components/core/src/components/pixano_inference_segmentation/inference.ts
ui/components/core/src/index.ts
ui/components/core/src/lib/types/index.ts
ui/components/core/src/lib/types/inference.ts
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/ImageViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VideoViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte
ui/components/datasetItemWorkspace/src/components/LoadModelModal.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
ui/components/vqaCanvas/src/features/manageModels/components/ConnectModal.svelte
ui/components/vqaCanvas/src/features/manageModels/components/ModelManagerForm.svelte

Allow SAM2 (or other segmentation model with same input / output) with Pixano Inference, using actual inputs
User is asked to enter either local or Pixano Inference model (in which case it can be added if not previously registered).
This is asked when clicking on the smart tool button if no model is set. Later you can access this panel with the "settings" button.
TODO:

Segmentation support with Pixano Inference

---

pixano/app/routers/inference/mask_generation.py
pixano/datasets/utils/mosaic.py
pixano/datasets/workspaces/dataset_items.py
pixano/inference/__init__.py
pixano/inference/mask_generation.py
tests/app/routers/test_inference/test_mask_generation.py
tests/datasets/utils/test_mosaic.py
tests/inference/test_mask_generation.py
ui/components/canvas2d/src/Canvas2D.svelte
ui/components/core/src/components/pixano_inference_segmentation/AddModelModal.svelte
ui/components/core/src/components/pixano_inference_segmentation/SelectLocalOrDistantModelModal.svelte
ui/components/core/src/components/pixano_inference_segmentation/inference.ts
ui/components/core/src/lib/types/inference.ts
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/DatasetItemViewer.svelte
ui/components/datasetItemWorkspace/src/components/SaveShape/SaveShapeForm.svelte
ui/components/datasetItemWorkspace/src/components/Toolbar.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/getFrameIndexFromViewRef.ts
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/index.ts
ui/components/vqaCanvas/src/features/manageModels/components/AddModelModal.svelte

Allow tracking with Pixano Inference.
TODO:

allow SAM2 tracking

---

ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/EntityLinkingViewer.svelte
ui/components/datasetItemWorkspace/src/components/DatasetItemViewer/VqaViewer.svelte

Default width for text panels in Entity Linking and VQA workspaces are too small.
Make them bigger

bigger default text panels widths

---

ui/apps/pixano/src/components/layout/DatasetItemHeader.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/VideoControls.svelte

* Since a lot of annotation actions in Pixano involve using the mouse in the right hand, add the option to navigate video frames with the left hand (WASD/ZQSD) rather than just with the right hand (Arrow keys)
* Replace `event.code` instead of `event.key` to be able to use the same physical keys regardless of keyboard layout (QWERTY, AZERTY, or other)

feat(front): Improve navigation keyboard shortcuts

---

ui/components/canvas2d/src/components/TextSpansContent.svelte
ui/components/datasetItemWorkspace/src/components/Features/UpdateFeatureInputs.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ChildCard.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/InspectorInspector.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectCard.svelte
ui/components/datasetItemWorkspace/src/components/Inspector/ObjectsModelSection.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/ObjectTracklet.svelte
ui/components/datasetItemWorkspace/src/components/VideoPlayer/TrackletKeyItem.svelte
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/deleteObject.ts
ui/components/datasetItemWorkspace/src/lib/api/objectsApi/scrollIntoView.ts
ui/components/datasetItemWorkspace/src/lib/stores/datasetItemWorkspaceStores.ts

Several bugfixes and enhancement on ObjectCard, ChilCard and VideoInspector.
Fixes #459 #513 #536 #552
Bugfixes:
Enhancements:

minor improvement/bugfixes on ObjectCard

---

pixano/datasets/queries/table.py
ui/components/core/src/api/getBrowser.ts

When updating some item feature, the updated rows become last.
We want to preserve order, so we order by date (using "created_at", the most reliable one as it should follow build order)
When no order is specified, always use order by 'created_at' (except if this column doesn't exist, for some old datasets)
Note: as lancedb search() doesn't support "order_by", we now use mostly duckdb sql search.
Also, bugfix in front (missing encodeURI for search filter)

order by created_at

---

pixano/datasets/dataset_info.py

dataset_preview.jpg image for Dataset Cards are often standard res image, /infos return a base64 image per dataset, which can potentially become big.
Make thumbnail back size to reduce payload.

thumbnail back side dataset_preview

---

pixano/app/routers/browser.py
pixano/datasets/queries/table.py
ui/apps/pixano/src/lib/stores/datasetStores.ts

With the default "created_at" sort, there was an order mismatch between the 20 rows displayed in Explorer, and the full list of ids (used to get index of item in current selection/filter/search, acces previous/next, etc.)
a test made to choose how to retrieve this full list was made BEFORE we replace "no sort" by default "created_at", so the list of ids was not sorted....
Fixed
Note: Except for rare case (after a refresh on a datasetItem page), we will probably always use the sorted version now.

fix ids order
